import js from "@eslint/js";
import eslintConfigPrettier from "eslint-config-prettier";

export default [
  js.configs.recommended,
  eslintConfigPrettier,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
        navigator: "readonly",
        location: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        clearTimeout: "readonly",
        fetch: "readonly",
        URL: "readonly",
        AbortSignal: "readonly",
        Intl: "readonly",
        Number: "readonly",
        Date: "readonly",
        JSON: "readonly",
        Promise: "readonly",
        Array: "readonly",
        Object: "readonly",
        RegExp: "readonly",
        Error: "readonly",
        Map: "readonly",
        Set: "readonly",
        WeakSet: "readonly",
        WeakMap: "readonly",
        Symbol: "readonly",
        Math: "readonly",
        Performance: "readonly",
        performance: "readonly",
        MutationObserver: "readonly",
        IntersectionObserver: "readonly",
        CustomEvent: "readonly",
        Navigation: "readonly",
        navigation: "readonly",
        globalThis: "readonly",
        chrome: "readonly",
        browser: "readonly",
        process: "readonly",
        SPPH_DEBUG: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "no-undef": "error",
      "no-console": "off",
      "prefer-const": "warn",
      "no-var": "error",
      "eqeqeq": ["error", "smart"],
      "curly": ["error", "multi-line"],
      "no-empty": ["error", { allowEmptyCatch: true }],
    },
  },
  {
    ignores: ["dist/", "node_modules/", "Chrome/", "Firefox/", "releases/"],
  },
];
